// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGEvecYa0ZUwcxwqcE9XJ_2YkK53vexU',
    appId: '1:512258355064:web:713e6c5485b9812d9da28d',
    messagingSenderId: '512258355064',
    projectId: 'istinyeuniversity-e260c',
    authDomain: 'istinyeuniversity-e260c.firebaseapp.com',
    storageBucket: 'istinyeuniversity-e260c.firebasestorage.app',
    measurementId: 'G-SWZ5Q0E7TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAToSF44S9oZhoe--AQsZfUHn8uBi4eY',
    appId: '1:512258355064:android:773a10cab9659c4c9da28d',
    messagingSenderId: '512258355064',
    projectId: 'istinyeuniversity-e260c',
    storageBucket: 'istinyeuniversity-e260c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOOxNAyvvYTjJrxgiAF51a19KxFmHfx0',
    appId: '1:512258355064:ios:c20287e7582e5e1b9da28d',
    messagingSenderId: '512258355064',
    projectId: 'istinyeuniversity-e260c',
    storageBucket: 'istinyeuniversity-e260c.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdOOxNAyvvYTjJrxgiAF51a19KxFmHfx0',
    appId: '1:512258355064:ios:c20287e7582e5e1b9da28d',
    messagingSenderId: '512258355064',
    projectId: 'istinyeuniversity-e260c',
    storageBucket: 'istinyeuniversity-e260c.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQGEvecYa0ZUwcxwqcE9XJ_2YkK53vexU',
    appId: '1:512258355064:web:bc42e2a7b44482e79da28d',
    messagingSenderId: '512258355064',
    projectId: 'istinyeuniversity-e260c',
    authDomain: 'istinyeuniversity-e260c.firebaseapp.com',
    storageBucket: 'istinyeuniversity-e260c.firebasestorage.app',
    measurementId: 'G-BDZ3PQWJL4',
  );
}
